// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onqdbnpzmohynahigjbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ucWRibnB6bW9oeW5haGlnamJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDA3NjIsImV4cCI6MjA3Mjk3Njc2Mn0.PX4G_o6_ICDnfaDHP5R-6uxDMZq8kSVMZm14ZMQDilI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});